version: '3.3'

services:
  whetupulse:
    image: whetupulse
    container_name: whetupulse
    restart: unless-stopped
    env_file: 
      - .env
    volumes:
      - C:\docker\whetupulse\data:/srv/whetupulse/data
      - C:\docker\whetupulse\ssh:/root/.ssh:ro
